In [2]:
import numpy as np
A=np.array([
    [2,5,7],
    [1,2,3],
    [7,4,2]
])
print(A)

[[2 5 7]
 [1 2 3]
 [7 4 2]]


In [3]:
import numpy as np
A=np.array([
    [2,5,7],
    [1,2,3],
    [7,4,2]
])
B=np.array([
    [8,0,5],
    [0,4,8],
    [1,0,6]
])
print(          A+B       )

[[10  5 12]
 [ 1  6 11]
 [ 8  4  8]]


In [4]:
import numpy as np
A=np.array([
    [2,5,7],
    [1,2,3],
    [7,4,2]
])
B=np.array([
    [8,0,5],
    [0,4,8],
    [1,0,6]
])
print(          A+B       )

[[10  5 12]
 [ 1  6 11]
 [ 8  4  8]]


In [5]:
import numpy as np
A=np.array([
    [2,5,7],
    [1,2,3],
    [7,4,2]
])
B=np.array([
    [8,0,5],
    [0,4,8],
    [1,0,6]
])
print(          A.dot(B)       )

[[23 20 92]
 [11  8 39]
 [58 16 79]]


In [6]:
import numpy as np
A=np.array([
    [2,5,7],
    [1,2,3],
    [7,4,2]
])
B=np.array([
    [8,0,5],
    [0,4,8],
    [1,0,6]
])
print(          np.dot(A,B)       )

[[23 20 92]
 [11  8 39]
 [58 16 79]]


In [7]:
import numpy as np
A=np.array([
    [2,5,7],
    [1,2,3],
    [7,4,2]
])
B=np.array([
    [8,0,5],
    [0,4,8],
    [1,0,6]
])
print(          np.matmul(A,B)       )

[[23 20 92]
 [11  8 39]
 [58 16 79]]


In [8]:
import numpy as np
A=np.array([
    [2,5,7],
    [1,2,3],
    [7,4,2]
])
print(      np.linalg.inv(A)   )

[[-0.88888889  2.          0.11111111]
 [ 2.11111111 -5.          0.11111111]
 [-1.11111111  3.         -0.11111111]]


In [9]:
import numpy as np
A=np.array([
    [2,5,7],
    [1,2,3],
    [7,4,2]
])
B=np.array([
    [8,0,5],
    [0,4,8],
    [1,0,6]
])
print(A*B)

[[16  0 35]
 [ 0  8 24]
 [ 7  0 12]]


In [10]:
import numpy as np
A=np.array([
    [2,5,7],
    [1,2,3],
    [7,4,2]
])
print(         np.linalg.eigvals(A)         )

[10.98868103 -4.81871355 -0.16996748]
